name: bgenv
channels:
  - defaults
dependencies:
  - python=3.11.5
  - ipykernel=6.25.0
  - matplotlib=3.8.1
  - nengo=3.2.0
  - nengo-extras=0.5.0
  - numpy=1.26.1
  - pandas=2.1.4
  - pytry=0.9.2
  - scikit-learn=1.3.2
  - scipy=1.11.3
